/**
 * @file ChangeProposal.model.ts
 * @module backend/models
 * @description Specification for Alternative Change Proposal Record generated by the Replanner.
 *
 * SCHEMA FIELDS & PARAMETERS:
 * - id: UUID (Primary Key)
 * - change_event_id: UUID (Foreign Key -> ChangeEvent.id)
 * - itinerary_id: UUID (Foreign Key -> Itinerary.id)
 * - operator_id: UUID (Proposing operator or system)
 * - proposal_type: Enum ['RESCHEDULE', 'SUBSTITUTE_SIMILAR', 'SUBSTITUTE_DIFFERENT', 'REMOVE_AND_COMPRESS', 'ADD_FREE_TIME']
 * - alternative_service_id: UUID (Null if removal; FK to Experience / Hotel / Transport)
 * - cost_delta: decimal (Positive = additional cost, Negative = refund)
 * - preference_match: Enum ['LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH']
 * - travel_delta_minutes: number (Additional travel time in minutes)
 * - schedule_shift_minutes: number (How much subsequent items shift)
 * - weather_risk: Enum ['LOW', 'MEDIUM', 'HIGH']
 * - approval_required: JSON Array of Enum ['TRAVELER', 'OPERATOR', 'ADMIN']
 * - explanation: JSON Object (structured trade-off: why_selected, cost_change, travel_change, operational_effect)
 * - status: Enum ['PENDING_REVIEW', 'APPROVED', 'REJECTED', 'EXPIRED']
 * - approved_by: JSON Array (list of actor IDs who approved)
 * - approved_at: Timestamp
 * - created_at: Timestamp
 *
 * RELATIONSHIPS:
 * - Belongs to ChangeEvent
 * - Results in new Itinerary version on approval
 *
 * INSTRUCTIONS:
 * - Every replanning scenario must produce at least 2 ranked proposals.
 * - explanation field must always be populated; it drives the UI trade-off display.
 * - High-impact proposals (approval_required includes OPERATOR) must NEVER auto-approve.
 */
